.TH "headers Directory Reference" 3 "Sun May 28 2023" "Version 2" "Estruturas de Dados Avançadas - trabalho prático" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBglobal\&.h\fP"
.br
.ti -1c
.RI "file \fBgraphs\&.h\fP"
.br
.ti -1c
.RI "file \fBrents\&.h\fP"
.br
.ti -1c
.RI "file \fBusers\&.h\fP"
.br
.ti -1c
.RI "file \fBvehicles\&.h\fP"
.br
.in -1c
