.TH "GraphList" 3 "Sun May 28 2023" "Version 2" "Estruturas de Dados Avançadas - trabalho prático" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphList
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBvertex\fP"
.br
.ti -1c
.RI "\fBAux\fP \fBvehicle\fP"
.br
.ti -1c
.RI "\fBEdge\fP * \fBedge\fP"
.br
.ti -1c
.RI "struct \fBGraphList\fP * \fBnextEntry\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBgraphs\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBEdge\fP* edge"

.PP
Definition at line \fB26\fP of file \fBgraphs\&.h\fP\&.
.SS "struct \fBGraphList\fP* nextEntry"

.PP
Definition at line \fB27\fP of file \fBgraphs\&.h\fP\&.
.SS "\fBAux\fP vehicle"

.PP
Definition at line \fB25\fP of file \fBgraphs\&.h\fP\&.
.SS "int vertex"

.PP
Definition at line \fB24\fP of file \fBgraphs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Estruturas de Dados Avançadas - trabalho prático from the source code\&.
