.TH "md__r_e_a_d_m_e" 3 "Sun May 28 2023" "Version 2" "Estruturas de Dados Avançadas - trabalho prático" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- EDA_tp01 
.PP
Trabalho prático de Estrutura de Dados Avançada
.SH "Documentation"
.PP
To see documentation go either to the folder:
.IP "\(bu" 2
documentation > html > \fCindex\&.html\fP
.IP "\(bu" 2
documentation > rtf > \fCrefman\&.rtf\fP
.PP
.SH "Roadmap"
.PP
.SS "Vehicles roadmap"
.IP "\(bu" 2
[x] Add vehicle to linked list
.IP "\(bu" 2
[x] List vehicles from linked list
.IP "\(bu" 2
[x] Delete vehicles from linked list
.IP "\(bu" 2
[x] Update vehicles from linked list
.IP "\(bu" 2
[x] Save vehicles to database
.IP "\(bu" 2
[x] Save vehicles to a binary database
.IP "\(bu" 2
[x] Get vehicles from database
.IP "\(bu" 2
[x] List vehicles by autonomy from linked list
.IP "\(bu" 2
[x] List vehicles by gps location from linked list
.IP "\(bu" 2
[x] Get vehicle by ID from linked list
.IP "\(bu" 2
[x] Recharge vehicles from linked list
.PP
.SS "Users roadmap"
.IP "\(bu" 2
[x] Add user to linked list
.IP "\(bu" 2
[x] Login user to program
.IP "\(bu" 2
[x] Save user to database
.IP "\(bu" 2
[x] Save user to a binary database
.IP "\(bu" 2
[x] Get user from database
.IP "\(bu" 2
[x] Delete user from linked list
.IP "\(bu" 2
[x] Update update from linked list
.PP
.SS "Rents roadmap"
.IP "\(bu" 2
[x] Add rent to linked list
.IP "\(bu" 2
[x] Save rents to database
.IP "\(bu" 2
[x] Save rents to a binary database
.IP "\(bu" 2
[x] Get rents from database
.IP "\(bu" 2
[x] Update rent from linked list
.IP "\(bu" 2
[x] List user rents from linked list
.IP "\(bu" 2
[x] List user active rents from linked list
.IP "\(bu" 2
[x] List all rents from linked list
.PP
.SS "Graphs roadmap"
.IP "\(bu" 2
[x] Add vertex to a linked list
.IP "\(bu" 2
[x] Add edges to a linked list
.IP "\(bu" 2
[x] Create random and dynamic graphs
.IP "\(bu" 2
[x] List graphs
.IP "\(bu" 2
[x] Save vertices to database
.IP "\(bu" 2
[x] Save vertices to a binary database
.IP "\(bu" 2
[x] Get vertices from database
.IP "\(bu" 2
[x] List vehicles in a given radius from the client
.IP "\(bu" 2
[ ] Calculate the shortest route to retrieve all vehicles with a battery lower than 50% 
.PP

